ass2: program.o LinkedList.o ShoppingCart.o ItemToPurchase.o

	g++ LinkedList.o ShoppingCart.o ItemToPurchase.o program.o -o ass2



program.o: program.cpp

	g++ -c -std=c++11 program.cpp


LinkedList.o: LinkedList.cpp

	g++ -c -std=c++11 LinkedList.cpp


ShoppingCart.o: ShoppingCart.cpp

	g++ -c -std=c++11 ShoppingCart.cpp

ItemToPurchase.o: ItemToPurchase.cpp

	g++ -c -std=c++11 ItemToPurchase.cpp
