ass8: digraph.o circle.o program.o

	g++ digraph.o circle.o program.o -o ass8



digraph.o: digraph.cpp

	g++ -c -std=c++11 digraph.cpp


circle.o: circle.cpp

	g++ -c -std=c++11 circle.cpp

program.o: program.cpp

	g++ -c -std=c++11 program.cpp


