ass4: program.o PriorityQueue.o CallCenter.o Call.o

	g++ PriorityQueue.o CallCenter.o Call.o program.o -o ass4



program.o: program.cpp

	g++ -c -std=c++11 program.cpp


PriorityQueue.o: PriorityQueue.cpp

	g++ -c -std=c++11 PriorityQueue.cpp


CallCenter.o: CallCenter.cpp

	g++ -c -std=c++11 CallCenter.cpp

Call.o: Call.cpp

	g++ -c -std=c++11 Call.cpp
