FLAGS = -std=c++14 -Wall -Wextra -pedantic -g -O

all: set1 set2 set3 set4 set5

.PHONY: set1 set2 set3 set4 set5

set1:
	g++ test1.cpp -o test1 $(FLAGS)

set2:
	g++ test2.cpp -o test2 $(FLAGS)

set3:
	g++ minimal.cpp -o minimal $(FLAGS)

set4:
	g++ performance.cpp -o performance $(FLAGS)

set5:
	g++ morse.cpp -o morse $(FLAGS)

